### PR TITLE
Add recent versions of Solidus to Travis

### PR DESCRIPTION
**Pull request by brchristian**

### CODE REVIEW

**Comment by brchristian** [comment]
Good point! Okay, I’ve updated it to be >= 2.4 and have force-pushed the new version.

**Comment by brchristian** [comment]
Hi @jhawthorn if you wouldn’t mind taking a look, could we get some of these approved PRs merged? I am highly motivated to get this extension passing its specs in recent versions of Solidus, and happy to help!

**Comment by jacobherrington** [comment]
Hey @brchristian Hawthorn isn't actively working on Solidus at the moment! 

On Solidusio repositories we have [a few requirements](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-requests) for merging PRs, one of those is that they require to approvals from Core Team members. 

Thanks a ton for contributing, I'll see if I can get some more feedback on these PRs.

@solidusio/core-team could we get a few people to take a look at this repo?

**Comment by kennyadsl** [comment]
@brchristian the Ci is failing and it look like a real issue. I also think we should also remove all the previous Solidus versions (<= 2.0) from travis.

**Comment by brchristian** [comment]
@kennyadsl I agree about removing old versions of Solidus, which I have submitted as PR https://github.com/solidusio/solidus_virtual_gift_card/pull/47.

The CI failures are due to a number of different causes, which I have been addressing in individual PRs, rather than as one monolithic PR that contains all the changes. For instance, https://github.com/solidusio/solidus_virtual_gift_card/pull/49 fixes an error with passing a class to `class_name`, https://github.com/solidusio/solidus_virtual_gift_card/pull/50 fixes an issue with the `before_filter` action, and https://github.com/solidusio/solidus_virtual_gift_card/pull/52 fixes an issue with migrations.

**Comment by kennyadsl** [comment]
@brchristian you are great!

**Pull request merged**
