### PR TITLE
Allow deleting of gift card line items with no arguments passed in

### PR DESCRIPTION
**Pull request by philbirt**
cc @allisonlarson @athal7

### CODE REVIEW

**Comment by athal7** [comment]
what if there are two gift cards? won't this delete the first one even if you are trying to delete the second one?

**Comment by philbirt** [comment]
Yeah, that is a concern. Unfortunately, there are a handful of places in solidus that do not pass options through (and in theory since they aren't required there could always be more in the future), so we have to assume that sometimes they won't be there. 

Since this such an edge/impossible case (Only one i can think of: > 1 line items with identical gift card variants, with different recipient information, in multiple shipments, removing from the admin shipments page or via the shipments api), I think it would probably be better to add to an existing line item/remove the first matching line item than throw an exception and show the user nothing.

There is a pretty robust interface for reviewing gift card information in the confirm step to make sure you deleted the thing you thought you deleted. I can also share stats I gathered on our past orders offline, if interested.

Apologies for the novel :)

**Comment by athal7** [comment]
I think I'm missing the multiple shipments piece, wouldn't it be within the same shipment? Like wouldn't this happen anytime you decrease quantity from 2 -> 1 ?

**Comment by philbirt** [comment]
Verbal :+1: from @athal7 this morning as a fallback. Going to also make a solidus change to further alleviate issues.

**Comment by jordan-brough** [comment]
Merging on behalf of @athal7

**Pull request merged**
